COLLECTION_NAME = "organization_policies" 
EMBEDDING_MODEL = "BAAI/bge-m3"
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
RETRIEVAL_K = 4
GEMINI_MODEL = "gemini-2.5-flash"
CLAUDE_CATEGORIZATION_MODEL = "claude-haiku-4-5-20251001"